In [3]:
import numpy as np
import pandas as pd

In [4]:
data1 = pd.read_csv('nyc_weather_2018.csv')
data2 = pd.read_csv('weather_stations.csv')
data = pd.merge(data1, data2, left_on='station',right_on='id')
data = data.drop_duplicates(subset=['station', 'datatype'])
data.head()

,date,datatype,station,attributes,value,id,name,latitude,longitude,elevation
0,2018-01-01T00:00:00,PRCP,GHCND:US1CTFR0039,",,N,",0.0,GHCND:US1CTFR0039,"STAMFORD 4.2 S, CT US",41.037788,-73.568176,6.4
3,2018-01-05T00:00:00,DAPR,GHCND:US1CTFR0039,",,N,",2.0,GHCND:US1CTFR0039,"STAMFORD 4.2 S, CT US",41.037788,-73.568176,6.4
4,2018-01-05T00:00:00,MDPR,GHCND:US1CTFR0039,",,N,",15.5,GHCND:US1CTFR0039,"STAMFORD 4.2 S, CT US",41.037788,-73.568176,6.4
5,2018-01-05T00:00:00,SNWD,GHCND:US1CTFR0039,",,N,",191.0,GHCND:US1CTFR0039,"STAMFORD 4.2 S, CT US",41.037788,-73.568176,6.4
17,2018-01-16T00:00:00,SNOW,GHCND:US1CTFR0039,",,N,",0.0,GHCND:US1CTFR0039,"STAMFORD 4.2 S, CT US",41.037788,-73.568176,6.4

In [5]:
snow = data.query(
    'datatype == "SNOW" and name.str.contains("NJ US")', engine='python')
snow.elevation.mean()

58.348484848484844

In [6]:
fb = pd.read_csv('fb.csv')
new_fb = fb.assign(pct_change=lambda x: x.volume.pct_change())
new_fb.sort_values(by='pct_change', ascending=False).head(5)

,date,high,low,open,close,volume,pct_change
8,2018-01-12,181.479996,177.399994,178.059998,179.369995,77551300,7.087865
52,2018-03-19,177.169998,170.059998,177.009995,172.559998,88140100,2.611796
142,2018-07-26,180.130005,173.750000,174.889999,176.259995,169803700,1.880265
182,2018-09-21,167.250000,162.809998,166.639999,162.929993,45994800,1.428961
57,2018-03-26,161.100006,149.020004,160.820007,160.059998,126116600,1.352496

In [7]:
data3 = pd.read_csv('earthquakes.csv')
new_data3 = data3[data3['magType'] == 'ml']
new_data3 = pd.cut(new_data3.mag, [0, 1, 2, 3, 4, 5])
new_data3.value_counts()

(1, 2]    3105
(0, 1]    2207
(2, 3]     862
(3, 4]     122
(4, 5]       2
Name: mag, dtype: int64

In [8]:
data4 = pd.read_csv('weather_by_station.csv')
data4['month'] = pd.DatetimeIndex(data4.date).month
pd.crosstab(index=data4.station, columns=data4.month, colnames=[
            'month'], values=data4.value, aggfunc=np.mean)

month,1,2,3,4,5,6,7,8,9,10,11,12
station,,,,,,,,,,,,
GHCND:US1CTFR0039,9.762857,9.906452,9.580556,14.082609,2.722581,6.368421,3.403226,7.220833,8.200000,3.893548,5.610000,6.659091
GHCND:US1NJBG0003,14.255556,23.450000,26.518750,9.742000,3.995000,1.461111,14.692308,7.789655,5.274419,1.745833,9.322000,3.839474
GHCND:US1NJBG0010,NaN,NaN,33.800000,18.437500,6.700000,7.700000,11.038462,21.400000,22.063636,13.340000,19.200000,NaN
GHCND:US1NJBG0015,6.207692,6.457143,7.910714,7.675000,2.075000,1.429787,2.884314,5.538462,6.066667,2.883784,9.421429,3.216327
GHCND:US1NJBG0017,11.339506,9.320000,13.038095,10.643137,2.520513,1.738636,3.200000,7.497222,4.684615,2.111905,10.506250,2.805455
...,...,...,...,...,...,...,...,...,...,...,...,...
GHCND:USW00054787,184.486022,165.691829,187.778136,184.116296,190.729749,176.979259,196.596057,193.315412,186.890741,194.390681,176.031769,185.034708
GHCND:USW00094728,50.235061,48.336184,37.296646,43.544923,42.488393,40.868210,40.636842,48.494203,26.306020,27.766809,5.556213,2.732143
GHCND:USW00094741,180.712143,175.291188,214.355282,201.150185,187.699283,203.008148,206.115412,213.606093,186.316296,201.343011,192.344211,179.765398
GHCND:USW00094745,180.765950,179.858984,188.500717,191.793704,187.332258,192.415556,190.816846,195.345520,165.255720,209.578495,194.783929,195.080069
GHCND:USW00094789,46.194183,44.171598,45.771067,42.063636,37.835150,35.905731,45.067867,42.044414,29.768391,47.119101,47.131161,41.066298

In [9]:
pd.crosstab(index=data4.station, columns=data4.month, colnames=['month'])

month               1    2    3    4    5    6    7    8    9    10   11   12
station
GHCND:US1CTFR0039   35   31   36   23   31   19   31   24   30   31   30   22
GHCND:US1NJBG0003    9   22   32   50   20   18   13   29   43   48   50   38
GHCND:US1NJBG0010    0    0    2    8   13   11   13   13   11    5    6    0
GHCND:US1NJBG0015   52   42   56   44   48   47   51   39   33   37   42   49
GHCND:US1NJBG0017   81   40   84   51   39   44   42   36   39   42   48   55
...                ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
GHCND:USW00054787  279  257  279  270  279  270  279  279  270  279  277  291
GHCND:USW00094728  328  304  328  325  336  324  342  345  299  235  169  168
GHCND:USW00094741  280  261  284  271  279  270  279  279  270  279  285  289
GHCND:USW00094745  279  256  279  270  279  270  279  279  271  279  280  291
GHCND:USW00094789  361  338  356  352  367  349  361  367  348  356  353  362

[109 rows x 12 columns]